### ISSUE TITLE
Lambdas with narrowed value

### ISSUE THREAD

**Issue by stefnotch** [otamam818/rustInterfaces#1]
So one complaint on Reddit was that this still needs an unwrap. Couldn't it just give you the value?
```ts
const msg = match( plate.variant, {
        // Values with 'Some' will return the internal value when unwrapped
        'Some': () => `Here eat your food: ${plate.unwrap()}`,
        'None': () => 'No food here yet'
    });
```

Well, if we made an option-specific match, then sure, it's easy.

But what if we want to keep the match as general as possible? Then it's hard. But still doable, because Typescript is wild.

I took a stab at a slightly simpler version of that, where I assume that the key is always called "variant". And yep, it's possible to get an API like this
```ts
// Look, msg is a string
const msg = matchVariant( plate, {
        'Some': (p) => `Here eat your food: ${p.value}`, // p has a value
        'None': (p) => `No food here yet ${p}` // p does not have a value
    });
```

Here's the Typescript playground demo
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcByEB2wAqAeHAPjgF44BvOANwEMoBLGzGALjgHINt2AaOAV0wB3KDTBsAFAEpSxHHAA+cbFWBQ4AXwBQoSLATJUAZQgBbXAWJlKtBk1YcT53tRoAbfsDY4+gkWMkZEjlNHXBoeCQUOAB5MBh6LHwiUnQsCxSlJwzCAG4tML14AGMsAGd4OISsACF+ejcAEzVU8i04ZXS2ADNBYurMOFMaAGtgLmBLaTYqxMxk4jaOjqhgGH4oQaXljttGZjZOdN52nYFhUXE4aVkKBAALKAghZWAXgFEoJ6gJACIANXcnjgjQgwDKmHY8FA9Aqvxk2h2iM0PFOZTMXjgvUw-TmQ1GwGyU1oHkxOCkM3icwWFFOKzWGy2dOWe3sh2y7DgNDKcFKmAqqLOrlJgrOfkugVuJM8zI0+Q62m0hQiWL6A3xMGK90BdmYBDgoBgwEwjR5Njo+wcFQYmAA5gpMPxTAAjNQKMqIF0QNwo3nleAAVQNICNJp5AFkaJr7gAFKP3MqWQgSCDOgBW3j4xW54LYAYpcEj0bjMATACUGZtEwHFqc+RU4GNEN4ANq-VnMX4AXVSqbTADoOzB5XBVutNryc2UW02uyn01yeUxEFJ8tooqgi1qSwn9Ybjaa7kO2Nb6HaHU7XVB3Z7nd7NFZaR0Z8BEHAz3AcG2h92u5IaN4cAAGRHhabKNq+mhBMQy5aHKWgboWUbbvGZQVuO-KWKk8j7mGcAVqUUCNHgy58Ge3QtEGuGHhI-Z0XQtplGwy7QVymCIMQAD8+GVvMhh4DWcBsCoaj5AhhhwAAwlGABiEAQIeZDsDggg0JySjsJJ9z0MUYyQooHBxrpazAI0cByQp7BaG4axwGAbhRqgZCzLU9RNGo-aYOkeDSTAFmmsmq5wAUAD0IVwAAMvJIx8KYZS2u+S5wKedpaPW8BxQlZDDNGOqWhIdkOUafDbEK7AcpIYCsQABgAEmoqDAFGcCIBAGxYvJjRsAAJOQYCDkCwAaNVfBhXZcD3NyXLCjKQodEc3CVTVGAdQpE0NS1tm9WAw1wGNYAgmCPJefAk2qNN0rALKq4FEAA

**Comment by otamam818** [comment]
Thanks for contributing!

This honestly feels more intuitive than what I provided. I'll be happy to add this as another function (`matchVariant` as you wrote), or if you want you can send in a pull request with this code.

**Comment by stefnotch** [comment]
Feel free to simply use it :)

I'm hereby releasing my code above under the CC0 licence. Now the licensing part is also sorted out and you're free to simply copy it.

**Comment by otamam818** [comment]
Ahahaha thanks a ton! :D
